In [ ]:
import pandas as pd
import numpy as np
data_gminy = pd.read_excel("C:\Users\Dell\dev\gus\2023_2040_9_gminy_ludnosc_-_tablica_zbiorcza_2.xlsx", dtype={"Kod_TERYT": str})
data_gminy.head()

,Kod_TERYT,Nazwa,Typ,Powiat,Województwo,Płeć,Wiek,2022,2023,2024,...,2031,2032,2033,2034,2035,2036,2037,2038,2039,2040
0,0201011,Bolesławiec,miejska,bolesławiecki,dolnośląskie,Ogółem,Ogółem,37293,36945,36617,...,34489,34154,33794,33437,33102,32746,32398,32052,31707,31375
1,0201011,Bolesławiec,miejska,bolesławiecki,dolnośląskie,Ogółem,0-17,5816,5720,5652,...,4903,4804,4714,4592,4496,4388,4308,4239,4166,4137
2,0201011,Bolesławiec,miejska,bolesławiecki,dolnośląskie,Ogółem,18-59/64,20919,20584,20279,...,19159,18955,18714,18454,18195,17945,17679,17368,17069,16673
3,0201011,Bolesławiec,miejska,bolesławiecki,dolnośląskie,Ogółem,18-44,12486,12142,11821,...,9790,9545,9275,9081,8881,8729,8624,8512,8405,8258
4,0201011,Bolesławiec,miejska,bolesławiecki,dolnośląskie,Ogółem,45-59/64,8433,8442,8458,...,9369,9410,9439,9373,9314,9216,9055,8856,8664,8415

In [19]:
data_gminy.columns.tolist()

['Kod_TERYT',
 'Nazwa',
 'Typ',
 'Powiat',
 'Województwo',
 'Płeć',
 'Wiek',
 2022,
 2023,
 2024,
 2025,
 2026,
 2027,
 2028,
 2029,
 2030,
 2031,
 2032,
 2033,
 2034,
 2035,
 2036,
 2037,
 2038,
 2039,
 2040]

to_list shows how the column should be adressed- with quotation marks or no

In [20]:
cities_total = data_gminy.loc[lambda d: (d["Płeć"] == "Ogółem") & (d["Wiek"] == "Ogółem") & (d["Typ"] == "miejska")].sort_values(by = 2022, ascending= False)
cities_total.head(10)

,Kod_TERYT,Nazwa,Typ,Powiat,Województwo,Płeć,Wiek,2022,2023,2024,...,2031,2032,2033,2034,2035,2036,2037,2038,2039,2040
39680,1465011,m. st. Warszawa,miejska,m. st. Warszawa,mazowieckie,Ogółem,Ogółem,1861975,1865772,1869447,...,1921491,1922424,1922325,1921646,1920570,1919260,1917864,1916437,1915033,1913717
29884,1261011,m. Kraków,miejska,m. Kraków,małopolskie,Ogółem,Ogółem,803282,806082,808780,...,833106,834270,834999,835453,835696,835774,835768,835676,835568,835448
5177,0264011,m. Wrocław,miejska,m. Wrocław,dolnośląskie,Ogółem,Ogółem,674079,674150,674123,...,684721,683481,681812,679890,677818,675642,673426,671146,668868,666590
24242,1061011,m. Łódź,miejska,m. Łódź,łódzkie,Ogółem,Ogółem,658444,653252,648050,...,615936,610311,604510,598650,592724,586746,580790,574817,568858,562932
73253,3064011,m. Poznań,miejska,m. Poznań,wielkopolskie,Ogółem,Ogółem,541316,538616,535862,...,523037,519562,515830,511966,508022,504012,499991,495954,491922,487917
54219,2261011,m. Gdańsk,miejska,m. Gdańsk,pomorskie,Ogółem,Ogółem,486345,487110,487822,...,495562,495369,494955,494407,493758,493018,492227,491401,490539,489666
76725,3262011,m. Szczecin,miejska,m. Szczecin,zachodniopomorskie,Ogółem,Ogółem,391566,389760,387922,...,379153,377069,374872,372607,370284,367926,365581,363199,360815,358432
16244,0663011,m. Lublin,miejska,m. Lublin,lubelskie,Ogółem,Ogółem,331243,330026,328776,...,322005,320475,318857,317190,315483,313753,312034,310303,308572,306837
9579,0461011,m. Bydgoszcz,miejska,m. Bydgoszcz,kujawsko-pomorskie,Ogółem,Ogółem,330038,326883,323749,...,305092,301952,298752,295534,292310,289097,285902,282722,279558,276422
50437,2061011,m. Białystok,miejska,m. Białystok,podlaskie,Ogółem,Ogółem,292600,291589,290556,...,283836,282588,281301,279990,278647,277289,275938,274573,273195,271825