In [1]:
column_types = {
"osm_id": "str",
"addr_street": "str",
"addr_number": "str",
"grupa_parter": "str",
"funkcja_parter": "str",
"grupa_pietra": "str",
"funkcja_pietra": "str",
"liczba_kondygnacji": "Int64",
"mieszana": "boolean",
"rok_budowy_szac": "Int64",
"styl_arch": "str",
"stan_tech": "Int64",
"wysokosc_max": "float64",
"zabytek": "str"
}

In [2]:
import pandas as pd
import numpy as np
pd.set_option("display.max_rows", 380)
data_gdynia = pd.read_csv("../data/raw/srodmiescie_raw.csv",
                          sep=";", index_col = 0, dtype = column_types)
data_clean = data_gdynia.drop(columns='Unnamed: 18')
data_clean.head()

,osm_id,addr_street,addr_number,grupa_parter,funkcja_parter,grupa_pietra,funkcja_pietra,liczba_kondygnacji,mieszana,rok_budowy_szac,styl_arch,stan_tech,wysokosc_max,zabytek,zrodlo,pewnosc,data_sprawdzenia
id,,,,,,,,,,,,,,,,,
1,127184291,Świętego Piotra,8,NaN,Hotel,NaN,Hotel,7,<NA>,2000,Współczesność,3,NaN,NaN,google.com/maps,3.0,27.09.2026
2,890729731,Świętego Piotra,6D,NaN,Mieszkaniowa Wielorodzinna,NaN,Mieszkaniowa Wielorodzinna,5,<NA>,2020,Współczesność,3,NaN,NaN,google.com/maps,3.0,27.09.2026
3,890292040,Węglowa,22,NaN,Centrum Handlowe,NaN,Mieszkaniowa Wielorodzinna,17,<NA>,2020,Współczesność,3,NaN,NaN,google.com/maps,3.0,27.09.2026
4,890729732,Świętego Piotra,6,NaN,Mieszkaniowa Wielorodzinna,NaN,Mieszkaniowa Wielorodzinna,17,<NA>,2020,Współczesność,3,NaN,NaN,google.com/maps,3.0,27.09.2026
5,136885205,Tadeusza Wendy,15,NaN,Centrum Medyczne,NaN,Centrum Medyczne,6,<NA>,2000,Współczesność,3,NaN,NaN,google.com/maps,2.0,27.09.2026

In [3]:
data_clean = data_clean.dropna(thresh = 3)
data_clean.isna().sum()

osm_id                   0
addr_street            267
addr_number            309
grupa_parter          1091
funkcja_parter           0
grupa_pietra          1105
funkcja_pietra         437
liczba_kondygnacji       0
mieszana              1105
rok_budowy_szac          0
styl_arch                0
stan_tech                0
wysokosc_max          1105
zabytek               1105
zrodlo                   0
pewnosc                  0
data_sprawdzenia         0
dtype: int64

In [10]:
data_clean["data_sprawdzenia"] =pd.to_datetime(data_clean["data_sprawdzenia"], format = '%d.%m.%Y')
data_clean.head()

,osm_id,addr_street,addr_number,grupa_parter,funkcja_parter,grupa_pietra,funkcja_pietra,liczba_kondygnacji,mieszana,rok_budowy_szac,styl_arch,stan_tech,wysokosc_max,zabytek,zrodlo,pewnosc,data_sprawdzenia
id,,,,,,,,,,,,,,,,,
1,127184291,Świętego Piotra,8,NaN,hotel,NaN,Hotel,7,<NA>,2000,Współczesność,3,NaN,NaN,google.com/maps,3.0,2026-09-27
2,890729731,Świętego Piotra,6D,NaN,mieszkaniowa wielorodzinna,NaN,Mieszkaniowa Wielorodzinna,5,<NA>,2020,Współczesność,3,NaN,NaN,google.com/maps,3.0,2026-09-27
3,890292040,Węglowa,22,NaN,centrum handlowe,NaN,Mieszkaniowa Wielorodzinna,17,<NA>,2020,Współczesność,3,NaN,NaN,google.com/maps,3.0,2026-09-27
4,890729732,Świętego Piotra,6,NaN,mieszkaniowa wielorodzinna,NaN,Mieszkaniowa Wielorodzinna,17,<NA>,2020,Współczesność,3,NaN,NaN,google.com/maps,3.0,2026-09-27
5,136885205,Tadeusza Wendy,15,NaN,centrum medyczne,NaN,Centrum Medyczne,6,<NA>,2000,Współczesność,3,NaN,NaN,google.com/maps,2.0,2026-09-27

Data Parsing excercise

In [5]:
data_clean["funkcja_parter"].value_counts().size

380

Number of values in basefloor functions

In [6]:
data_clean["funkcja_parter"] = data_clean["funkcja_parter"].str.lower().str.strip().str.replace("_"," ")
data_clean["funkcja_parter"].value_counts()

funkcja_parter
garaż                                                                                                       216
mieszkaniowa wielorodzinna                                                                                   79
restauracja                                                                                                  51
nieużytek                                                                                                    36
biurowa                                                                                                      28
mieszkaniowa jednorodzinna                                                                                   22
pustka                                                                                                       20
techniczne                                                                                                   18
techniczna                                                                                                   16
centrum medyczne                                                                                             14
magazynowa                                                                                                   12
handel ubrania                                                                                               12
żabka                                                                                                        12
centrum handlowe                                                                                             11
bar                                                                                                          11
portowa                                                                                                       9
klub muzyczny                                                                                                 9
targ                                                                                                          9
cukiernia                                                                                                     9
bank                                                                                                          8
hurtownia                                                                                                     7
administracyjna                                                                                               7
kawiarnia                                                                                                     7
szpital                                                                                                       6
dworzec kolejowy                                                                                              6
hotel                                                                                                         5
przedszkole                                                                                                   5
straż pożarna                                                                                                 5
piekarnia                                                                                                     5
przychodnia                                                                                                   5
restauracja,bank                                                                                              5
usługi transport                                                                                              4
lumpeks                                                                                                       4
kebab                                                                                                         4
sąd                                                                                                           4
restauracja,nieużytek                                                                                         4
apteka                                                                                                        4
pub                                                                                                           4
delikatesy                                                                                                    4
lodziarnia                                                                                                    4
szkoła żeglarska                                                                                              4
sklep monopolowy                                                                                              3
usługi techniczne                                                                                             3
handlowa                                                                                                      3
szkoła podstawowa                                                                                             3
kiosk                                                                                                         3
warsztat samochodowy                                                                                          3
usługowa                                                                                                      3
hostel                                                                                                        3
biblioteka                                                                                                    3
wojskowa                                                                                                      3
kantor                                                                                                        3
pizzeria                                                                                                      3
restauracja,handel pamiątki                                                                                   3
dentysta                                                                                                      3
kościół                                                                                                       3
biedronka                                                                                                     3
optyk                                                                                                         3
empik                                                                                                         3
apartament turystyczny                                                                                        2
sakralna                                                                                                      2
fryzjer                                                                                                       2
policja                                                                                                       2
usługi medyczne                                                                                               2
usługi zdrowie,centrum medyczne,żabka,piekarnia                                                               2
komis sztuki                                                                                                  2
sklep spożywczy                                                                                               2
stomatolog                                                                                                    2
notariusz                                                                                                     2
biuro obsługi klienta zkm                                                                                     2
administracja                                                                                                 2
serwis rowerowy                                                                                               2
usługi szkolenia                                                                                              2
handlowa ubrania                                                                                              2
restauracja,fryzjer                                                                                           2
usługowa kursy                                                                                                2
usługowa zdrowie                                                                                              2
spółdzielnia mieszkaniowa                                                                                     2
sexshop                                                                                                       2
aparthotel                                                                                                    2
poczta                                                                                                        2
drogeria                                                                                                      2
handlowa kwiaty,żabka                                                                                         2
biurowa, usługowa medyczna                                                                                    2
informacja                                                                                                    2
księgarnia                                                                                                    2
fryzjer,restauracja                                                                                           2
klub nocny                                                                                                    2
nieużytek,restauracja                                                                                         2
liceum                                                                                                        2
wystawowa                                                                                                     1
hotel,restauracja                                                                                             1
cukiernia,usługi medyczne                                                                                     1
handel rowery,usługi reklamy                                                                                  1
usługi zdrowie                                                                                                1
konsultat kultury                                                                                             1
handel medyczne, żabka                                                                                        1
apteka,bank                                                                                                   1
usługi medyczne,handel ubrania                                                                                1
rehabilitacja                                                                                                 1
szkoła policealna,administracja                                                                               1
informacja autobusowa                                                                                         1
dentysta,fryzjer                                                                                              1
dentysta,nieużytek                                                                                            1
sklep wielobranżowy,bank,usługi zdrowie                                                                       1
zegarmistrz,handlowa epapierosy                                                                               1
handlowa sprzęt,handlowa zdrowie                                                                              1
żłobek                                                                                                        1
lombard                                                                                                       1
handlowa sprzęt                                                                                               1
dentysta,dermatolog,restauracja                                                                               1
kaplica                                                                                                       1
handlowa meble                                                                                                1
fundacja                                                                                                      1
piekarnia,sklep wielobranżowy,usługowa krawiec                                                                1
stokrotka, drogeria, usługowa                                                                                 1
restauracja, delikatesy                                                                                       1
usługowa pralnia,handlowa księgarnia                                                                          1
piekarnia,lombard,bar                                                                                         1
ubezpieczenia                                                                                                 1
restauracja,adwokat, handel komputery                                                                         1
usługowa telko                                                                                                1
handel odzierz,manicure                                                                                       1
handel papierniczy                                                                                            1
dworzec kolejowy,rossman,mcdonald                                                                             1
usługowa krawiec,usługowa wycieczki                                                                           1
handlowa ubrania,nieużytek                                                                                    1
handlowa ubrania,usługowa zdrowie                                                                             1
restauracja,usługowa zdrowie                                                                                  1
apteka,kawiarnia                                                                                              1
handlowa ubrania,usługowa fotograf                                                                            1
warzywniak,handlowa ubrania,usługowa zdrowie                                                                  1
piekarnia,usługi ubezpieczenia,usługi jubiler                                                                 1
stowarzyszenie kulturalne                                                                                     1
apteka, fryzjer, kantor                                                                                       1
fryzjer,usługowa                                                                                              1
żabka,kawiarnia,handel ubrania                                                                                1
fryzjer,handlowa,nieużytek                                                                                    1
usługi kursy                                                                                                  1
apteka,handlowa                                                                                               1
handlowa turystyczna                                                                                          1
apteka,delikatesy,księgarnia,zakład pogrzebowy                                                                1
restauracja,lombarz                                                                                           1
usługowa masaż                                                                                                1
stomatolog,kawiarnia                                                                                          1
handel księgarnia                                                                                             1
żabka,usługowa masaż                                                                                          1
restauracja,fryzjer,bank                                                                                      1
restauracja,centrum medyczne                                                                                  1
fryzjer,usługowa biuro podróż                                                                                 1
handlowa sztka, apteka, żabka, cukiernia,lumpeks                                                              1
gimnazjum                                                                                                     1
usługowa medyczna                                                                                             1
bar,usługowa                                                                                                  1
usługowa zdrowie,kantor                                                                                       1
handlowa zdrowie                                                                                              1
usługowa,żabka,restauracja                                                                                    1
pub,bar,usługi zdrowie                                                                                        1
lombard, usługi foto                                                                                          1
instytut meteorologii                                                                                         1
usługowa pralnia,barber                                                                                       1
klub bilardowy                                                                                                1
piekarnia, jubiler,kantor                                                                                     1
lombard,restauracja                                                                                           1
zus                                                                                                           1
usługowa medyczna,usługowa złotnik,kawiarnia                                                                  1
handlowa ubrania,usługowa krawiec                                                                             1
gimnazjum,administracja                                                                                       1
handlowa muzyka, centrum medyczne                                                                             1
usługowa nieruchomośći                                                                                        1
piekarnia,handel                                                                                              1
usługowa zdrowie,handel ubrania                                                                               1
centrum medyczne,sex shop                                                                                     1
handlowa medyczna,handlowa filatelistyka,restauracja                                                          1
usługowa krawiec,usługowa fotograf                                                                            1
spa                                                                                                           1
fryzjer,biuro nieruchomosci                                                                                   1
kawiarnia,biuro rachunkowe                                                                                    1

In [7]:
data_clean["funkcja_parter"].str.count(',').value_counts()

funkcja_parter
0    876
1    150
2     55
3     17
4      4
5      2
7      1
Name: count, dtype: int64

Number of functions per row

In [8]:
mask = data_clean["funkcja_parter"].str.count(',') == 7
data_clean.loc[mask,["funkcja_parter"] ]

                                        funkcja_parter
id
959  piekarnia,żabka,handel medyczny,centrum medycy...

The id of the building with most functions = 8, based on how many , were in the column

In [9]:
(data_clean["funkcja_parter"].str.count(',')+1).sum()

np.int64(1449)

Number of all functions in the file