In [ ]:
import pandas as pd
import numpy as np
data_gdynia = pd.read_csv("../data/raw/srodmiescie_raw.csv", sep=";", index_col = 0)
data_gdynia.head()

,osm_id,addr_street,addr_number,grupa_parter,funkcja_parter,grupa_pietra,funkcja_pietra,liczba_kondygnacji,mieszana,rok_budowy_szac,styl_arch,stan_tech,wysokosc_max,zabytek
id,,,,,,,,,,,,,,
1,127184291,Świętego Piotra,8,NaN,Hotel,NaN,Hotel,7.0,NaN,NaN,NaN,NaN,28.8,NaN
2,890729731,Świętego Piotra,6D,NaN,Mieszkaniowa Wielorodzinna,NaN,Mieszkaniowa Wielorodzinna,5.0,NaN,NaN,NaN,NaN,23.8,NaN
3,890292040,Węglowa,22,NaN,Centrum Handlowe,NaN,Mieszkaniowa Wielorodzinna,17.0,NaN,NaN,NaN,NaN,58.5,NaN
4,890729732,Świętego Piotra,6,NaN,Mieszkaniowa Wielorodzinna,NaN,Mieszkaniowa Wielorodzinna,17.0,NaN,NaN,NaN,NaN,59.4,NaN
5,136885205,Tadeusza Wendy,15,NaN,Centrum Medyczne,NaN,Centrum Medyczne,6.0,NaN,NaN,NaN,NaN,31.1,NaN

1.Series and Dataframe, types based on the brackets

In [ ]:
print(data_gdynia.index.is_unique)
print(type(data_gdynia.osm_id))
print(type(data_gdynia["osm_id"]))
print(type(data_gdynia[["osm_id"]]))

True
<class 'pandas.Series'>
<class 'pandas.Series'>
<class 'pandas.DataFrame'>

by adding another column bracket the type turns into DataFrame

2.Loc and Iloc, difference in searching the same row of data

In [ ]:
print(data_gdynia.loc[615])
print(data_gdynia.iloc[614])

osm_id                                 126117711
addr_street                         Świętojańska
addr_number                                   18
grupa_parter                                 NaN
funkcja_parter             Restauracja,Cukiernia
grupa_pietra                                 NaN
funkcja_pietra        Mieszkaniowa_Wielorodzinna
liczba_kondygnacji                           0.0
mieszana                                     NaN
rok_budowy_szac                           1930.0
styl_arch                              Modernizm
stan_tech                                    2.0
wysokosc_max                                27.2
zabytek                                      NaN
Name: 615, dtype: object
osm_id                                 126117711
addr_street                         Świętojańska
addr_number                                   18
grupa_parter                                 NaN
funkcja_parter             Restauracja,Cukiernia
grupa_pietra                                 NaN
funkcja_pietra        Mieszkaniowa_Wielorodzinna
liczba_kondygnacji                           0.0
mieszana                                     NaN
rok_budowy_szac                           1930.0
styl_arch                              Modernizm
stan_tech                                    2.0
wysokosc_max                                27.2
zabytek                                      NaN
Name: 615, dtype: object

Iloc returns the row by index, loc by the name of the row,
in order to get row number 614, the iloc needs number 615, since it starts with 0

3.Sorting the buildings by height and showing the 5 highest with its osm id

In [ ]:
sorted_height = data_gdynia.sort_values(by ="wysokosc_max", ascending = False).osm_id
sorted_height[:5]

id
271     76208008
793    260675986
4      890729732
3      890292040
399    355431246
Name: osm_id, dtype: int64

4.Masking the values with iloc and & in in the DataFrame

In [ ]:
functions = ["Restauracja", "Kawiarnia", "Bar"]
data_gdynia.loc[(data_gdynia.addr_street == "Starowiejska") & (data_gdynia.funkcja_parter.isin(functions)),["addr_street", "addr_number", "funkcja_parter", "liczba_kondygnacji"]]

      addr_street addr_number funkcja_parter  liczba_kondygnacji
id
309  Starowiejska           8    Restauracja                 3.0
331  Starowiejska          30    Restauracja                 2.0
335  Starowiejska         40G    Restauracja                 2.0
336  Starowiejska          28    Restauracja                 5.0
339  Starowiejska          30    Restauracja                 2.0
365  Starowiejska          60            Bar                 1.0
367  Starowiejska         40C    Restauracja                 2.0
381  Starowiejska           1    Restauracja                 5.0

loc can get multiple statements, to filter the values in rows as well as collumns

5.Checking whether there are collumns that have all NaN values

In [ ]:
missing_per_column = data_gdynia.isna().sum()
mask = missing_per_column == len(data_gdynia)
data_gdynia.loc[:,mask]

      grupa_pietra  mieszana
id
1              NaN       NaN
2              NaN       NaN
3              NaN       NaN
4              NaN       NaN
5              NaN       NaN
...            ...       ...
1237           NaN       NaN
1238           NaN       NaN
1239           NaN       NaN
1240           NaN       NaN
1241           NaN       NaN

[1241 rows x 2 columns]

A method to get the rows that are full of NaN values

In [ ]:
empty_cols = data_gdynia.columns[mask]
data_gdynia_deleted_cols = data_gdynia.drop(empty_cols,axis = 1)
print(data_gdynia.shape)
print(data_gdynia_deleted_cols.shape)

(1241, 14)
(1241, 12)

Function drop deletes the rows or columns specified in the function

6.Counting the buildings without the argument in the collumn

In [ ]:
labeled_buildings_number = data_gdynia.addr_street.value_counts().sum()
no_labeled_buildings_number = len(data_gdynia) - data_gdynia.addr_street.value_counts().sum()
print(no_labeled_buildings_number)

486

A method to find number of buildings that are not labeled in the column

7.Ranking of buildings

In [ ]:
data_gdynia.addr_street.value_counts().rank(ascending = False)

addr_street
Świętojańska                              1.0
Antoniego Abrahama                        2.0
Starowiejska                              3.0
Wójta Radtkego                            4.0
Władysława IV                             5.0
Stefana Żeromskiego                       6.0
10 Lutego                                 7.0
Jerzego Waszyngtona                       8.0
Kazimierza Pułaskiego                     9.0
Armii Krajowej                           10.0
Jana z Kolna                             11.0
3 Maja                                   12.0
Świętego Piotra                          13.0
Plac Kaszubski                           14.5
Zgoda                                    14.5
Portowa                                  16.5
Jana Kilińskiego                         16.5
Generała Józefa Bema                     18.0
Mściwoja                                 19.5
Franciszka Żwirki i Stanisława Wigury    19.5
Tadeusza Wendy                           22.5
Arkadiusza Rybickiego                    22.5
Skwer Tadeusza Kościuszki                22.5
Stefana Batorego                         22.5
Śledziowa                                25.5
Zygmunta Augusta                         25.5
Hieronima Derdowskiego                   28.0
Aleja Jana Pawła II                      28.0
Obrońców Wybrzeża                        28.0
Plac Konstytucji                         30.5
Plac Grunwaldzki                         30.5
Dworcowa                                 32.5
Juliusza Słowackiego                     32.5
Świętego Wojciecha                       34.5
Żołnierzy I Armii Wojska Polskiego       34.5
Romualda Traugutta                       36.5
Aleja Marszałka Józefa Piłsudskiego      36.5
Węglowa                                  42.0
Wendy                                    42.0
Plac Kaszubski - Jana z Kolna            42.0
Janka Wiśniewskiego                      42.0
Antoniego Hryniewickiego                 42.0
Nabrzeże Prezydenta                      42.0
Szkolna                                  42.0
Zygmuntowska                             42.0
Józefa Wybickiego                        42.0
Name: count, dtype: float64

8.Filling the values in subtraction between two series create series without NaN

In [ ]:
no_parter = data_gdynia.funkcja_parter.value_counts()
no_pietro = data_gdynia.funkcja_pietra.value_counts()
no_parter.sub(no_pietro, fill_value= 0)

funkcja_parter
????????                      0.0
Administracja                 1.0
Administracyjna               1.0
Apartament Turystyczny        0.0
Aparthotel                    0.0
                             ...
Żabka,Kosmetyczka,Okulista    1.0
Żabka,Restauracja             1.0
Żabka,Usługi Medyczne         1.0
Żabka,Usługowa                1.0
Żłobek                        0.0
Name: count, Length: 236, dtype: float64

Withou fill value, if either one of the collumns taking part in substraction has NaN value the resoult is NaN, no matter the value of the second number

9.Adding another columnindex to reindex adds the column with the NaN or fill values

In [ ]:
n_o_buildings = data_gdynia.addr_street.value_counts()
streets = ["Świętojańska", "Starowiejska", "Jantarowa"]
n_o_buildings.reindex(streets, fill_value= 0)

dtype('int64')

Series with NaN values is always Float, where filled one is Int

10.Calculation of data corellation

In [ ]:
data_gdynia["wysokosc_max"].corr(data_gdynia["liczba_kondygnacji"])

np.float64(0.7989515914106871)

The correlation is really heigh despite the error values in the building heights, it can be higher but corellation can look good