In [1]:
import pandas as pd
import numpy as np
from math import e
import matplotlib.pyplot as plt

pd.set_option("display.max_colwidth", None)
pd.set_option("display.max_rows", 200)
pd.set_option("display.max_columns", None)


column_types = {
    "id": "Int64",
    "osm_id": "str",
    "addr_street": "str",
    "addr_number": "str",
    "ground_floor_group": "str",
    "ground_floor_function": "str",
    "upper_floor_group": "str",
    "upper_floor_function": "str",
    "number_of_storeys": "Int64",
    "is_mixed_use": "boolean",
    "build_year_est": "Int64",
    "arch_style": "str",
    "condition": "Int64",
    "max_height": "float64",
    "is_heritage": "str",
    "source": "str",
    "confidence": "Int64",
    "date_of_checking": "str",
    "number_of_functions": "Int64",
}

In [2]:
data_gdynia = pd.read_csv(
    "../data/processed/fixed/srodmiescie.csv",
    sep=";",
    index_col=0,
    dtype=column_types,
    parse_dates=["date_of_checking"],
)

1.

In [3]:
cumulative_dates = (
    data_gdynia.resample("D", on="date_of_checking")
    .agg(
        num_buildings=("osm_id", "size"),
    )
    .assign(cum_buildings=lambda d: d["num_buildings"].cumsum())
    .assign(cum_share=lambda d: d["cum_buildings"].div(len(data_gdynia)))
)
cumulative_dates

                  num_buildings  cum_buildings  cum_share
date_of_checking
2026-09-23                   52             52   0.052953
2026-09-24                  108            160   0.162933
2026-09-25                   67            227   0.231161
2026-09-26                  100            327   0.332994
2026-09-27                  461            788   0.802444
2026-09-28                    0            788   0.802444
2026-09-29                   22            810   0.824847
2026-09-30                  172            982   1.000000

In [4]:
(cumulative_dates["cum_share"] > 0.50).idxmax()

Timestamp('2026-09-27 00:00:00')

2.

In [5]:
date_resample = (
    data_gdynia.resample("D", on="date_of_checking")
    .agg(
        num_buildings=("osm_id", "size"),
    )
    .assign(num_diff=lambda d: d["num_buildings"].diff())
)
date_resample

                  num_buildings  num_diff
date_of_checking
2026-09-23                   52       NaN
2026-09-24                  108      56.0
2026-09-25                   67     -41.0
2026-09-26                  100      33.0
2026-09-27                  461     361.0
2026-09-28                    0    -461.0
2026-09-29                   22      22.0
2026-09-30                  172     150.0

In [6]:
data_gdynia.groupby("date_of_checking").agg(
    num_buildings=("osm_id", "size"),
).assign(num_diff=lambda d: d["num_buildings"].diff())

                  num_buildings  num_diff
date_of_checking
2026-09-23                   52       NaN
2026-09-24                  108      56.0
2026-09-25                   67     -41.0
2026-09-26                  100      33.0
2026-09-27                  461     361.0
2026-09-29                   22    -439.0
2026-09-30                  172     150.0

In [7]:
print(
    f"the biggest decline was: {date_resample.loc[date_resample['num_diff'].idxmin(), 'num_diff']} on the day of: {date_resample['num_diff'].idxmin()}"
)
print(
    f"the biggest increase was: {date_resample.loc[date_resample['num_diff'].idxmax(), 'num_diff']} on the day of: {date_resample['num_diff'].idxmax()}"
)

the biggest decline was: -461.0 on the day of: 2026-09-28 00:00:00
the biggest increase was: 361.0 on the day of: 2026-09-27 00:00:00

In [8]:
assert (
    date_resample["num_diff"].fillna(date_resample["num_buildings"].iloc[0]).cumsum()
    == date_resample["num_buildings"]
).all()

3.

In [9]:
date_resample_shift = (
    data_gdynia.resample("D", on="date_of_checking")
    .agg(
        num_buildings=("osm_id", "size"),
    )
    .assign(num_prev_day=lambda d: d["num_buildings"].shift())
    .assign(num_diff=lambda d: d["num_buildings"] - d["num_prev_day"])
    .assign(day_perc_change=lambda d: d["num_buildings"] / d["num_prev_day"] - 1)
    .assign(pct_change=lambda d: d["num_buildings"].pct_change())
)
date_resample_shift

,num_buildings,num_prev_day,num_diff,day_perc_change,pct_change
date_of_checking,,,,,
2026-09-23,52,NaN,NaN,NaN,NaN
2026-09-24,108,52.0,56.0,1.076923,1.076923
2026-09-25,67,108.0,-41.0,-0.379630,-0.379630
2026-09-26,100,67.0,33.0,0.492537,0.492537
2026-09-27,461,100.0,361.0,3.610000,3.610000
2026-09-28,0,461.0,-461.0,-1.000000,-1.000000
2026-09-29,22,0.0,22.0,inf,inf
2026-09-30,172,22.0,150.0,6.818182,6.818182

In [10]:
assert np.isinf(date_resample_shift["pct_change"]).sum() == 1
assert date_resample_shift["pct_change"].isna().sum() == 1

pd.testing.assert_series_equal(
    date_resample_shift["day_perc_change"],
    date_resample_shift["pct_change"],
    check_names=False,
)

pd.testing.assert_series_equal(
    date_resample_shift["num_diff"], date_resample["num_diff"]
)

4.

In [11]:
str_date_cumsum = (
    data_gdynia.groupby(["addr_street", "date_of_checking"])
    .size()
    .to_frame("num_buildings")
    .assign(num_cumsum=lambda d: d.groupby("addr_street").cumsum())
)
str_date_cumsum.tail()

                                                     num_buildings  num_cumsum
addr_street                        date_of_checking
Świętojańska                       2026-09-26                   10          11
                                   2026-09-27                   35          46
                                   2026-09-29                   11          57
                                   2026-09-30                   49         106
Żołnierzy I Armii Wojska Polskiego 2026-09-30                    3           3

In [12]:
assert (str_date_cumsum.loc["Świętojańska", "num_cumsum"] == [1, 11, 46, 57, 106]).all()
assert (
    data_gdynia.groupby(["addr_street", "date_of_checking"])
    .size()
    .to_frame("num_buildings")
    .cumsum()
    .loc["Świętojańska", "num_buildings"][-1:]
    == 710
).all()

assert (
    data_gdynia.groupby("addr_street")["date_of_checking"].nunique().eq(1).sum() == 16
)

pd.testing.assert_series_equal(
    data_gdynia.groupby(["addr_street", "date_of_checking"])
    .size()
    .to_frame("num_buildings")
    .groupby("addr_street")
    .cumsum()
    .groupby("addr_street")
    .tail(1)
    .sort_values("num_buildings", ascending=False)
    .reset_index()
    .set_index("addr_street")
    .loc[:, "num_buildings"]
    .sort_index(),
    data_gdynia["addr_street"].value_counts().sort_index(),
    check_names=False,
)

5.

In [ ]:
date_visit_diff = (
    data_gdynia.groupby(["addr_street", "date_of_checking"])
    .size()
    .reset_index(name="num_build")
    .assign(
        visit_diff=lambda d: d.groupby("addr_street")["date_of_checking"].diff().dt.days
    )
)
date_visit_diff.head()

  addr_street date_of_checking  num_build  visit_diff
0   10 Lutego       2026-09-24         24         NaN
1   10 Lutego       2026-09-26          8         2.0
2   10 Lutego       2026-09-27          5         1.0
3   10 Lutego       2026-09-30          1         3.0
4      3 Maja       2026-09-23          6         NaN

In [ ]:
assert len(date_visit_diff) == 96
assert date_visit_diff.isna().sum().sum() == 44
assert (date_visit_diff.groupby("addr_street").size() >= 2).sum() == 28
assert date_visit_diff["visit_diff"].value_counts().to_dict() == {
    1: 24,
    2: 15,
    3: 11,
    4: 2,
}
assert (
    date_visit_diff.loc[date_visit_diff["visit_diff"] == 4, "addr_street"]
    == ["Antoniego Hryniewickiego", "Plac Konstytucji"]
).all()
assert (
    data_gdynia.groupby(["addr_street", "date_of_checking"])
    .size()
    .reset_index()
    .loc[:, "date_of_checking"]
    .diff()
    .dt.days.lt(0)
    .sum()
    == 27
)

6.

In [ ]:
date_visit_diff2 = date_visit_diff.assign(
    prev_visit=lambda d: d.groupby("addr_street")["date_of_checking"].shift()
).assign(visit_diff2=lambda d: (d["date_of_checking"] - d["prev_visit"]).dt.days)

In [ ]:
pd.testing.assert_series_equal(
    date_visit_diff2["visit_diff"], date_visit_diff2["visit_diff2"], check_names=False
)

assert (
    date_visit_diff2.loc[
        date_visit_diff2["addr_street"] == "Świętojańska", "date_of_checking"
    ]
    == pd.to_datetime(
        ["2026-09-24", "2026-09-26", "2026-09-27", "2026-09-29", "2026-09-30"]
    )
).all()

In [17]:
date_visit_diff2

,addr_street,date_of_checking,num_build,visit_diff,prev_visit,visit_diff2
0,10 Lutego,2026-09-24,24,NaN,NaT,NaN
1,10 Lutego,2026-09-26,8,2.0,2026-09-24,2.0
2,10 Lutego,2026-09-27,5,1.0,2026-09-26,1.0
3,10 Lutego,2026-09-30,1,3.0,2026-09-27,3.0
4,3 Maja,2026-09-23,6,NaN,NaT,NaN
5,3 Maja,2026-09-24,10,1.0,2026-09-23,1.0
6,3 Maja,2026-09-27,5,3.0,2026-09-24,3.0
7,Aleja Jana Pawła II,2026-09-24,1,NaN,NaT,NaN
8,Aleja Jana Pawła II,2026-09-27,14,3.0,2026-09-24,3.0
9,Aleja Marszałka Józefa Piłsudskiego,2026-09-30,2,NaN,NaT,NaN
10,Antoniego Abrahama,2026-09-23,1,NaN,NaT,NaN
11,Antoniego Abrahama,2026-09-26,21,3.0,2026-09-23,3.0
12,Antoniego Abrahama,2026-09-27,23,1.0,2026-09-26,1.0
13,Antoniego Abrahama,2026-09-29,2,2.0,2026-09-27,2.0
14,Antoniego Abrahama,2026-09-30,23,1.0,2026-09-29,1.0
15,Antoniego Hryniewickiego,2026-09-23,5,NaN,NaT,NaN
16,Antoniego Hryniewickiego,2026-09-27,18,4.0,2026-09-23,4.0
17,Arkadiusza Rybickiego,2026-09-27,9,NaN,NaT,NaN
18,Armii Krajowej,2026-09-24,6,NaN,NaT,NaN
19,Armii Krajowej,2026-09-25,5,1.0,2026-09-24,1.0
20,Armii Krajowej,2026-09-27,6,2.0,2026-09-25,2.0
21,Armii Krajowej,2026-09-30,8,3.0,2026-09-27,3.0
22,Dworcowa,2026-09-24,1,NaN,NaT,NaN
23,Dworcowa,2026-09-27,3,3.0,2026-09-24,3.0
24,Franciszka Żwirki i Stanisława Wigury,2026-09-27,4,NaN,NaT,NaN
25,Franciszka Żwirki i Stanisława Wigury,2026-09-29,2,2.0,2026-09-27,2.0
26,Franciszka Żwirki i Stanisława Wigury,2026-09-30,4,1.0,2026-09-29,1.0
27,Generała Józefa Bema,2026-09-30,11,NaN,NaT,NaN
28,Hieronima Derdowskiego,2026-09-25,3,NaN,NaT,NaN
29,Hieronima Derdowskiego,2026-09-27,3,2.0,2026-09-25,2.0
30,Hilarego Jastaka,2026-09-25,1,NaN,NaT,NaN
31,Jana Kilińskiego,2026-09-29,5,NaN,NaT,NaN
32,Jana Kilińskiego,2026-09-30,8,1.0,2026-09-29,1.0
33,Jana z Kolna,2026-09-26,3,NaN,NaT,NaN
34,Jana z Kolna,2026-09-27,21,1.0,2026-09-26,1.0
35,Janka Wiśniewskiego,2026-09-27,3,NaN,NaT,NaN
36,Jerzego Waszyngtona,2026-09-25,5,NaN,NaT,NaN
37,Jerzego Waszyngtona,2026-09-26,1,1.0,2026-09-25,1.0
38,Jerzego Waszyngtona,2026-09-27,17,1.0,2026-09-26,1.0
39,Jerzego Waszyngtona,2026-09-30,1,3.0,2026-09-27,3.0
40,Juliusza Słowackiego,2026-09-30,4,NaN,NaT,NaN
41,Józefa Wybickiego,2026-09-27,1,NaN,NaT,NaN
42,Kazimierza Pułaskiego,2026-09-25,1,NaN,NaT,NaN
43,Kazimierza Pułaskiego,2026-09-27,12,2.0,2026-09-25,2.0
44,Mściwoja,2026-09-23,5,NaN,NaT,NaN
45,Mściwoja,2026-09-24,5,1.0,2026-09-23,1.0
46,Obrońców Wybrzeża,2026-09-24,2,NaN,NaT,NaN
47,Obrońców Wybrzeża,2026-09-27,2,3.0,2026-09-24,3.0
48,Obrońców Wybrzeża,2026-09-30,3,3.0,2026-09-27,3.0
49,Plac Grunwaldzki,2026-09-26,2,NaN,NaT,NaN
50,Plac Grunwaldzki,2026-09-27,4,1.0,2026-09-26,1.0
51,Plac Kaszubski,2026-09-23,1,NaN,NaT,NaN
52,Plac Kaszubski,2026-09-25,11,2.0,2026-09-23,2.0
53,Plac Kaszubski,2026-09-27,1,2.0,2026-09-25,2.0
54,Plac Konstytucji,2026-09-23,1,NaN,NaT,NaN
55,Plac Konstytucji,2026-09-27,10,4.0,2026-09-23,4.0
56,Portowa,2026-09-26,2,NaN,NaT,NaN
57,Portowa,2026-09-27,11,1.0,2026-09-26,1.0
58,Romualda Traugutta,2026-09-27,1,NaN,NaT,NaN
59,Romualda Traugutta,2026-09-30,1,3.0,2026-09-27,3.0
60,Skwer Tadeusza Kościuszki,2026-09-27,12,NaN,NaT,NaN
61,Starowiejska,2026-09-23,17,NaN,NaT,NaN
62,Starowiejska,2026-09-24,3,1.0,2026-09-23,1.0
63,Starowiejska,2026-09-26,8,2.0,2026-09-24,2.0
64,Starowiejska,2026-09-27,25,1.0,2026-09-26,1.0
65,Stefana Batorego,2026-09-24,5,NaN,NaT,NaN
66,Stefana Batorego,2026-09-25,2,1.0,2026-09-24,1.0
67,Stefana Batorego,2026-09-27,1,2.0,2026-09-25,2.0
68,Stefana Żeromskiego,2026-09-25,8,NaN,NaT,NaN
69,Stefana Żeromskiego,2026-09-26,1,1.0,2026-09-25,1.0
70,Stefana Żeromskiego,2026-09-27,18,1.0,2026-09-26,1.0
71,Szkolna,2026-09-24,1,NaN,NaT,NaN
72,Tadeusza Wendy,2026-09-27,7,NaN,NaT,NaN
73,Wójta Radtkego,2026-09-23,3,NaN,NaT,NaN
74,Wójta Radtkego,2026-09-25,5,2.0,2026-09-23,2.0
75,Wójta Radtkego,2026-09-27,31,2.0,2026-09-25,2.0
76,Węglowa,2026-09-27,1,NaN,NaT,NaN
77,Władysława IV,2026-09-24,9,NaN,NaT,NaN
78,Władysława IV,2026-09-25,2,1.0,2026-09-24,1.0
79,Władysława IV,2026-09-26,2,1.0,2026-09-25,1.0
80,Władysława IV,2026-09-27,13,1.0,2026-09-26,1.0
81,Władysława IV,2026-09-30,11,3.0,2026-09-27,3.0
82,Zgoda,2026-09-23,4,NaN,NaT,NaN
83,Zgoda,2026-09-24,7,1.0,2026-09-23,1.0
84,Zygmunta Augusta,2026-09-26,7,NaN,NaT,NaN
85,Zygmuntowska,2026-09-27,1,NaN,NaT,NaN
86,Śledziowa,2026-09-27,9,NaN,NaT,NaN
87,Świętego Piotra,2026-09-27,10,NaN,NaT,NaN
88,Świętego Wojciecha,2026-09-25,1,NaN,NaT,NaN
89,Świętego Wojciecha,2026-09-27,1,2.0,2026-09-25,2.0
90,Świętojańska,2026-09-24,1,NaN,NaT,NaN
91,Świętojańska,2026-09-26,10,2.0,2026-09-24,2.0
92,Świętojańska,2026-09-27,35,1.0,2026-09-26,1.0
93,Świętojańska,2026-09-29,11,2.0,2026-09-27,2.0
94,Świętojańska,2026-09-30,49,1.0,2026-09-29,1.0
95,Żołnierzy I Armii Wojska Polskiego,2026-09-30,3,NaN,NaT,NaN

In [ ]:
data_gdynia.groupby(['addr_street','arch'])