In [1]:
import pandas as pd
import numpy as np

column_types = {
    "id": "Int64",
    "osm_id": "str",
    "addr_street": "str",
    "addr_number": "str",
    "ground_floor_group": "str",
    "ground_floor_function": "str",
    "upper_floor_group": "str",
    "upper_floor_function": "str",
    "number_of_storeys": "Int64",
    "is_mixed_use": "boolean",
    "build_year_est": "Int64",
    "arch_style": "str",
    "condition": "Int64",
    "max_height": "float64",
    "is_heritage": "str",
    "source": "str",
    "confidence": "Int64",
    "date_of_checking": "str",
}

In [2]:
data_gdynia = pd.read_csv(
    "../data/raw/srodmiescie_raw.csv", sep=";", index_col=0, dtype=column_types
).dropna(subset="ground_floor_function")

data_gdynia.head(20)

,osm_id,addr_street,addr_number,ground_floor_group,ground_floor_function,upper_floor_group,upper_floor_function,number_of_storeys,is_mixed_use,build_year_est,arch_style,condition,max_height,is_heritage,source,confidence,date_of_checking
id,,,,,,,,,,,,,,,,,
1,127184291,Świętego Piotra,8,NaN,Hotel,NaN,Hotel,7,<NA>,2000,Współczesność,3,NaN,NaN,google.com/maps,3,27.09.2026
2,890729731,Świętego Piotra,6D,NaN,Mieszkaniowa Wielorodzinna,NaN,Mieszkaniowa Wielorodzinna,5,<NA>,2020,Współczesność,3,NaN,NaN,google.com/maps,3,27.09.2026
3,890292040,Węglowa,22,NaN,Centrum Handlowe,NaN,Mieszkaniowa Wielorodzinna,17,<NA>,2020,Współczesność,3,NaN,NaN,google.com/maps,3,27.09.2026
4,890729732,Świętego Piotra,6,NaN,Mieszkaniowa Wielorodzinna,NaN,Mieszkaniowa Wielorodzinna,17,<NA>,2020,Współczesność,3,NaN,NaN,google.com/maps,3,27.09.2026
5,136885205,Tadeusza Wendy,15,NaN,Centrum Medyczne,NaN,Centrum Medyczne,6,<NA>,2000,Współczesność,3,NaN,NaN,google.com/maps,2,27.09.2026
6,273937994,Tadeusza Wendy,15,NaN,Biurowa,NaN,Biurowa,9,<NA>,2000,Współczesność,3,NaN,NaN,google.com/maps,2,27.09.2026
7,398139557,Tadeusza Wendy,15,NaN,Biurowa,NaN,Biurowa,1,<NA>,2000,Współczesność,3,NaN,NaN,google.com/maps,2,27.09.2026
8,273937986,Tadeusza Wendy,15,NaN,Biurowa,NaN,Biurowa,8,<NA>,2000,Współczesność,3,NaN,NaN,google.com/maps,2,27.09.2026
9,126117723,Świętego Piotra,19,NaN,Bar,NaN,Mieszkaniowa Wielorodzinna,5,<NA>,1930,Modernizm,2,NaN,NaN,google.com/maps,2,27.09.2026
10,273937982,Tadeusza Wendy,15,NaN,Usługi_Transport,NaN,Usługi_Transport,5,<NA>,2000,Współczesność,3,NaN,NaN,google.com/maps,2,27.09.2026
11,398139480,Świętego Piotra,21,NaN,Centrum Medyczne,NaN,Biura,5,<NA>,1930,Modernizm,2,NaN,NaN,google.com/maps,2,27.09.2026
12,273937989,Tadeusza Wendy,15,NaN,Usługi_Transport,NaN,Usługi_Transport,2,<NA>,2000,Współczesność,3,NaN,NaN,google.com/maps,2,27.09.2026
13,127184289,Świętego Piotra,17,NaN,Wystawowa,NaN,Mieszkaniowa Wielorodzinna,5,<NA>,1950,Modernizm,2,NaN,NaN,google.com/maps,2,27.09.2026
14,127110175,Portowa,3,NaN,Sklep Monopolowy,NaN,Mieszkaniowa Wielorodzinna,6,<NA>,1940,Modernizm,2,NaN,NaN,google.com/maps,2,27.09.2026
15,127184288,Świętego Piotra,15,NaN,Usługi Techniczne,NaN,Usługi Techniczne,4,<NA>,1950,Modernizm,2,NaN,NaN,google.com/maps,2,27.09.2026
16,398139521,Świętego Piotra,19,NaN,Bar,NaN,NaN,1,<NA>,1930,Modernizm,2,NaN,NaN,google.com/maps,2,27.09.2026
17,398139538,Świętego Piotra,19,NaN,Bar,NaN,NaN,1,<NA>,1930,Modernizm,2,NaN,NaN,google.com/maps,2,27.09.2026
18,127184286,Świętego Piotra,13,NaN,Apartament Turystyczny,NaN,Apartament Turystyczny,5,<NA>,1950,Modernizm,2,NaN,NaN,google.com/maps,2,27.09.2026
19,127184285,Świętego Piotra,11,NaN,Mieszkaniowa Wielorodzinna,NaN,Mieszkaniowa Wielorodzinna,5,<NA>,1950,Modernizm,2,NaN,NaN,google.com/maps,2,27.09.2026
20,126117726,Stefana Żeromskiego,1,NaN,Mieszkaniowa Jednorodzinna,NaN,Mieszkaniowa Jednorodzinna,2,<NA>,1950,Modernizm,2,NaN,NaN,google.com/maps,2,27.09.2026

In [3]:
data_extract = (
    data_gdynia.assign(
        funkcja_parter=lambda d: (
            d["ground_floor_function"]
            .str.replace("_", " ")
            .str.lower()
        ))
)

Exercise 1: Number of groups

In [4]:
num_streets = data_extract.groupby('addr_street').ngroups
print(f"number of individual streets: {num_streets}")
data_extract.groupby('addr_street').get_group('Stefana Batorego').head()

number of individual streets: 48

,osm_id,addr_street,addr_number,ground_floor_group,ground_floor_function,upper_floor_group,upper_floor_function,number_of_storeys,is_mixed_use,build_year_est,arch_style,condition,max_height,is_heritage,source,confidence,date_of_checking,funkcja_parter
id,,,,,,,,,,,,,,,,,,
710,260800820,Stefana Batorego,28-30,NaN,Biurowa,NaN,Biurowa,9,<NA>,1980,Postmodernizm,3,NaN,NaN,google.com/maps,2,24.09.2026,biurowa
711,126357614,Stefana Batorego,28-30,NaN,"Biurowa, Usługowa Medyczna",NaN,Biurowa,9,<NA>,1980,Postmodernizm,3,NaN,NaN,google.com/maps,2,24.09.2026,"biurowa, usługowa medyczna"
715,260800816,Stefana Batorego,28-30,NaN,"Biurowa, Usługowa Medyczna",NaN,Biurowa,9,<NA>,1980,Postmodernizm,3,NaN,NaN,google.com/maps,2,24.09.2026,"biurowa, usługowa medyczna"
728,126343902,Stefana Batorego,20,NaN,Usługi_Tatuaże,NaN,Mieszkaniowa Wielorodzinna,6,<NA>,1950,Modernizm,2,NaN,NaN,google.com/maps,2,24.09.2026,usługi tatuaże
731,126343905,Stefana Batorego,24,NaN,Mieszkaniowa Wielorodzinna,NaN,Mieszkaniowa Wielorodzinna,6,<NA>,1950,Modernizm,2,NaN,NaN,google.com/maps,2,24.09.2026,mieszkaniowa wielorodzinna

In [5]:
assert num_streets == data_extract["addr_street"].nunique()

Exercise 2:Number of buildings per street in 2 methods

In [6]:
num_count = data_extract.groupby('addr_street')['addr_number'].count()
num_size = data_extract.groupby('addr_street').size()
num_value_counts = data_extract['addr_street'].value_counts()
diff = num_count - num_size
diff[diff != 0]

addr_street
3 Maja                     -2
Antoniego Abrahama         -1
Antoniego Hryniewickiego   -1
Armii Krajowej             -1
Hilarego Jastaka           -1
Hryniewickiego             -5
Jana z Kolna               -4
Kazimierza Pułaskiego      -1
Nabrzeże Prezydenta        -1
Obrońców Wybrzeża          -1
Plac Konstytucji           -5
Portowa                    -2
Starowiejska               -4
Stefana Batorego           -1
Stefana Żeromskiego        -1
Wendy                      -1
Wójta Radtkego             -1
Zygmunta Augusta           -1
Śledziowa                  -8
dtype: int64

In [7]:
assert num_size.sort_index().equals(num_value_counts.sort_index())

Exercise 3 grupby by 2 keys

In [8]:
len_group = data_extract.groupby(['addr_street','condition']).size().sum()
print(len_group)

mask = data_extract['addr_street'].isna() | data_extract['source'].isna()
print(mask.sum())

837
268

In [9]:
assert (mask.sum()+ len_group) == len(data_extract)

Exercise 4 aggregated functions per buildings per streets

In [10]:
data_extract = data_extract.assign(num_func=lambda d: d['funkcja_parter'].str.count(',')+1) #adding another collumn based on the number of functions per building
data_extract.groupby('addr_street')['num_func'].agg(['size','min','max','mean']).head()

                                     size  min  max      mean
addr_street
10 Lutego                              48    1    3  1.333333
3 Maja                                 26    1    2  1.230769
Aleja Jana Pawła II                    15    1    2  1.333333
Aleja Marszałka Józefa Piłsudskiego     3    1    1  1.000000
Antoniego Abrahama                     80    1    5  1.550000

In [11]:
data_extract.groupby('addr_street')['num_func'].get_group('Aleja Jana Pawła II').describe()

count    15.000000
mean      1.333333
std       0.487950
min       1.000000
25%       1.000000
50%       1.000000
75%       2.000000
max       2.000000
Name: num_func, dtype: float64

Exercise 5 Further aggregation

In [12]:
data_extract.groupby('num_func', as_index=False).agg(
    n_buildings =('addr_street', 'size'),
    unique_streets = ('addr_street','nunique' ),
    n_fill_address = ('addr_number', 'count')
)

   num_func  n_buildings  unique_streets  n_fill_address
0         1          876              45             569
1         2          150              28             148
2         3           55              13              54
3         4           17               6              17
4         5            4               2               4
5         6            2               2               2
6         8            1               1               1

Exercise 6 Aggregation with custom function

In [13]:
def max_min(arr):
    return arr.max() - arr.min()

cust_func_1 = data_extract.groupby('addr_street')['num_func'].agg(max_min)
cust_func_2 = data_extract.groupby('addr_street')['num_func'].agg(lambda s: s.max() - s.min())

In [14]:
assert cust_func_1.equals(cust_func_2)

Exercise 7 transform

In [15]:
data_extract = data_extract.assign(n_on_street = data_extract.groupby('addr_street')['osm_id'].transform('size'))
mask = data_extract['n_on_street'] >= 10
buildings_str_min_10 = data_extract[mask]

In [16]:
assert len(data_extract) == 1105
assert buildings_str_min_10['n_on_street'].min() >= 10