In [1]:
import pandas as pd
import numpy as np

column_types = {
    "id": "Int64",
    "osm_id": "str",
    "addr_street": "str",
    "addr_number": "str",
    "ground_floor_group": "str",
    "ground_floor_function": "str",
    "upper_floor_group": "str",
    "upper_floor_function": "str",
    "number_of_storeys": "Int64",
    "is_mixed_use": "boolean",
    "build_year_est": "Int64",
    "arch_style": "str",
    "condition": "Int64",
    "max_height": "float64",
    "is_heritage": "str",
    "source": "str",
    "confidence": "Int64",
    "date_of_checking": "str",
}

In [2]:
data_gdynia = pd.read_csv(
    "../../data/processed/fixed/srodmiescie.csv",
    sep=";",
    index_col=0,
    dtype=column_types,
    parse_dates=["date_of_checking"],
)
data_gdynia.head()

,osm_id,addr_street,addr_number,ground_floor_group,ground_floor_function,upper_floor_group,upper_floor_function,number_of_storeys,is_mixed_use,build_year_est,arch_style,condition,max_height,is_heritage,source,confidence,date_of_checking
id,,,,,,,,,,,,,,,,,
1,127184291,Świętego Piotra,8,NaN,hotel,NaN,Hotel,7,<NA>,2000,współczesność,3,NaN,NaN,google.com/maps,3,2026-09-27
2,890729731,Świętego Piotra,6D,NaN,mieszkaniowa wielorodzinna,NaN,Mieszkaniowa Wielorodzinna,5,<NA>,2020,współczesność,3,NaN,NaN,google.com/maps,3,2026-09-27
3,890292040,Węglowa,22,NaN,centrum handlowe,NaN,Mieszkaniowa Wielorodzinna,17,<NA>,2020,współczesność,3,NaN,NaN,google.com/maps,3,2026-09-27
4,890729732,Świętego Piotra,6,NaN,mieszkaniowa wielorodzinna,NaN,Mieszkaniowa Wielorodzinna,17,<NA>,2020,współczesność,3,NaN,NaN,google.com/maps,3,2026-09-27
5,136885205,Tadeusza Wendy,15,NaN,centrum medyczne,NaN,Centrum Medyczne,6,<NA>,2000,współczesność,3,NaN,NaN,google.com/maps,2,2026-09-27

In [3]:
data_gdynia_long = pd.read_csv(
    "../../data/processed/fixed/srodmiescie_long.csv",
    sep=";",
    index_col=0,
    dtype=column_types,
)
data_gdynia_long.head()

        addr_street       ground_floor_function
id
1   Świętego Piotra                       hotel
2   Świętego Piotra  mieszkaniowa wielorodzinna
3           Węglowa            centrum handlowe
4   Świętego Piotra  mieszkaniowa wielorodzinna
5    Tadeusza Wendy            centrum medyczne

In [4]:
data_gdynia = data_gdynia.assign(
    n_func_building = lambda d: d['ground_floor_function'].str.count(',')+1,
    is_multifunc = lambda d: d['n_func_building'] >1
)
locals = data_gdynia.groupby('addr_street').agg(
    n_locals_street = ('is_multifunc', 'size'),
    share_multifunc = ('is_multifunc', 'mean')
)
funct = data_gdynia_long.groupby('addr_street').agg(
    n_uniq_func = ('ground_floor_function', 'nunique')
)
score = locals.join(funct)
score = score[['n_locals_street', 'n_uniq_func', 'share_multifunc']]

In [5]:
data_gdynia_long.groupby('addr_street').agg(
    n_uniq_func = ('ground_floor_function', 'nunique'))

                                       n_uniq_func
addr_street
10 Lutego                                       42
3 Maja                                          21
Aleja Jana Pawła II                              8
Aleja Marszałka Józefa Piłsudskiego              3
Antoniego Abrahama                              71
Antoniego Hryniewickiego                         8
Arkadiusza Rybickiego                            7
Armii Krajowej                                  26
Dworcowa                                         6
Franciszka Żwirki i Stanisława Wigury           18
Generała Józefa Bema                            10
Hieronima Derdowskiego                           5
Hilarego Jastaka                                 1
Jana Kilińskiego                                14
Jana z Kolna                                    20
Janka Wiśniewskiego                              1
Jerzego Waszyngtona                             14
Juliusza Słowackiego                             1
Józefa Wybickiego                                2
Kazimierza Pułaskiego                            5
Mściwoja                                        12
Nabrzeże Prezydenta                              1
Obrońców Wybrzeża                               10
Plac Grunwaldzki                                 7
Plac Kaszubski                                  16
Plac Konstytucji                                12
Portowa                                          8
Romualda Traugutta                               4
Skwer Tadeusza Kościuszki                       14
Starowiejska                                    45
Stefana Batorego                                11
Stefana Żeromskiego                             14
Szkolna                                          4
Tadeusza Wendy                                   5
Wójta Radtkego                                  26
Węglowa                                          1
Władysława IV                                   48
Zgoda                                            7
Zygmunta Augusta                                 9
Zygmuntowska                                     1
Śledziowa                                        2
Świętego Piotra                                  8
Świętego Wojciecha                               3
Świętojańska                                    93
Żołnierzy I Armii Wojska Polskiego               4